# Generated by Django 5.2.8 on 2025-11-10 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('pair_address', models.CharField(max_length=100, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.BigIntegerField()),
                ('volume_24h', models.BigIntegerField()),
                ('liquidity', models.BigIntegerField()),
                ('price_change_24h', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_change_1h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_change_7d', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('recommendation', models.CharField(choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('AVOID', 'Avoid')], default='HOLD', max_length=5)),
                ('analysis_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('volatility_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stop_loss_level', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('suggested_position_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-analysis_score', '-volume_24h'],
            },
        ),
    ]
